apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: wp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: wp
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-wp-secret
              key: db-password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wp-persistent-volume
          mountPath: /var/www/html
    volumes:
    - name: wp-persistent-volume
      persistentVolumeClaim:
        claimName: wp-pvc