apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  selector:
    app: helloworld-web
  ports:
  - name:  helloworld-web
    port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-web
  template:
    metadata:
      labels:
        app: helloworld-web
    spec:
      containers:
        - name: helloworld
          image: boploi/boploi