apiVersion: autoscaling/v1
kind: HorizontalPodsAutoscaler
metadata:
  name: hpa-example-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-example
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50