apiVersion: v1
kind: LimitRange
metadata:
  name: limits-default
  namespace: quota-space
spec:
  limits:
    - default:
        cpu: 200m
        memory: 0.5Gi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      type: Container