apiVersion: apps/v1
kind: Deployment
metadata:
  name: quota-helloworld
  namespace: quota-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld-quota
  template:
    metadata:
      labels:
        app: helloworld-quota
    spec:
      containers:
        - name: k8s-demo
          image: wardviaene/k8s-demo
          ports:
            - name: nodejs-port
              containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 0.5Gi
            limits:
              cpu: 400m
              memory: 1Gi