apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /statefulData
    type: DirectoryOrCreate