apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/sql
    type: DirectoryOrCreate