apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sonarqube
spec:
  selector:
    matchLabels:
      db: postgresdb
  serviceName: "postgresdb"
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
        db: postgresdb
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
          - containerPort: 5432
            name: postgresdb
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-sonarqube
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: postgres-sonarqube
          - name: POSTGRES_DB
            value: "sonardb"
          - name: PGDATA
            value: /var/lib/postgresql/data/sonardb
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc